services:
  web:
    # container_name: django_app_dev
    volumes:
      - .:/app # Mount local source code for live updates
      # - /tmp:/tmp
    ports:
      - "8000:8000"
    command: python src/manage.py runserver 0.0.0.0:8000 # Dev server
    env_file:
      - .env.dev
    environment:
      - DEBUG=1

  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    ports:
      - "6379:6379"
    env_file:
      - .env.dev
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  celery_worker:
    volumes:
      - .:/app
    command: celery -A project worker --loglevel=debug # Verbose logging for development
    env_file:
      - .env.dev
    environment:
      - DEBUG=1

  nginx:
    ports:
      - "80:80" # Same port mapping for simplicity
    volumes:
      - ./config/nginx/default.config.template:/etc/nginx/conf.d/default.conf
      - .:/app
