services:
  web:
    build: .
    container_name: django_app
    command: ["./wait-for-it.sh", "db:5432","--","python", "/app/src/manage.py", "runserver","0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # load the environment variables from .env
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env # load the environment variables from .env
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}