services:
  web:
    build: .
    container_name: django_app
    command: ["./wait-for-it.sh", "db:5432","--","python", "/app/src/manage.py", "runserver","0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # load the environment variables from .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    env_file:
      - .env # load the environment variables from .env
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}