services:
  web:
    image: rasterzoo/ecom:v0.0.5
    container_name: django_app
    expose:
      - "8000"
    command: ["./wait-for-it.sh", "db:5432","--", "uwsgi","--ini", "/app/config/uwsgi/uwsgi.ini"]
    restart: always
    env_file:
      - .env.prod # load the environment variables from .env

  db:
    env_file:
      - .env.prod # load the environment variables from .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    env_file:
      - .env.prod
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

  rabbitmq:
    env_file:
      - .env.prod
    # ports: # TODO:
    #   - "5672:5672"
    #   - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  celery_worker:
    image: rasterzoo/ecom:v0.0.5
    command: celery -A project worker --loglevel=info
    env_file:
      - .env.prod
    user: ${CELERY_USER}

  nginx:
    volumes:
      - ./config/nginx/default.config.template:/etc/nginx/conf.d/default.conf
      # - .:/app
    ports:
      - "80:80"
      - "443:443"
