# Generated by Django 5.0.9 on 2024-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tag_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='shop_tag_name_971c74_idx'),
        ),
    ]
