# Generated by Django 5.0.9 on 2024-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_city_profile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
